---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```


New approach for gris. 


```{r}
library(spbabel) ## devtools::install_github("mdsumner/spbabel")
library(dplyr)
source("R/grist.r")
library(maptools)
data(wrld_simpl)
#install.packages("rworldxtra")
library(rworldxtra)
data(countriesHigh)

d <- countriesHigh
d1<- as.data.frame(d) %>% mutate(object_ = row_number())
map1 <- sptable(d) 

x <- gris2(d1, map1)

verts <- with(x, o %>% filter(NAME == "Japan") %>% select(object_) %>% inner_join(b) %>% inner_join(bXv) %>% inner_join(v))
library(ggplot2)
ggplot(verts) + aes(x = x_, y = y_, fill = branch_, group = branch_) + geom_polygon()



## say we add the segments, then subset
x$s <- grist(x)
xa <- list(o =x$o %>% filter(NAME == "Japan"))
xa$b <- inner_join(x$b, xa$o %>% select(object_))
xa$bXv <- inner_join(x$bXv, xa$b %>% select(branch_))
xa$v <- inner_join(x$v, xa$bXv %>% select(vertex_)) %>% distinct()
xa$s <- inner_join(x$s, xa$b %>% select(branch_))

verts <- with(xa, o %>% select(object_) %>% inner_join(b) %>% inner_join(bXv) %>% inner_join(v))
library(ggplot2)
ggplot(verts) + aes(x = x_, y = y_, fill = branch_, group = branch_) + geom_polygon()



tr <- RTriangle::triangulate(p = RTriangle::pslg(xa$v %>% dplyr::select(x_, y_) %>% as.matrix(), 
                                                 S = seg2struct(xa) %>% as.matrix()),                                               a = 0.1)

plot(tr$P, pch = ".")
apply(tr$T, 1, function(a) lines(tr$P[a, ]))
```


Try conversion from other formats. 

```{r}
library(spatstat)
  # polygon with hole
  ho <- owin(poly=list(list(x=c(0,1,1,0), y=c(0,0,1,1)),
                       list(x=c(0.6,0.4,0.4,0.6), y=c(0.2,0.2,0.4,0.4))))
  
as_df_bdry <- function(x) {
  bind_rows(lapply(x$bdry, function(xb) data_frame(x_ = xb$x, y_ = xb$y)), .id = "branch_")
}


as_df_bdry(ho)
as_df_branch_bdry(ho)



```